on:
- push
- pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: |
          if [[ "$(go fmt)" ]]; then
            echo "Go files were not formatted properly"
            exit 1
          fi
          go build
          go test
          go vet
      - uses: dominikh/staticcheck-action@v1
        with:
          version: 2023.1.6
          install-go: false
      - if: success() && github.ref == 'refs/heads/main'
        uses: ncruces/go-coverage-report@v0
